version: "3.8"
services:
  postgres:
    image: postgres:15
    container_name: lombra-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: teste123@
      POSTGRES_DB: lombra_delivery
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
